# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "ko-KR"
title: "더블제이 블로그"
name: "Double J"
description: "Capturing the moments in everyday life I wish I could pause."
url: "https://doodle-jj.github.io"
baseurl: ""

# Author
author:
  name: "Double J"
  bio: "Capturing the moments in everyday life I wish I could pause."

# Pagination
paginate: 5
paginate_path: /page:num/

# Defaults (Post 기본 설정)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true

# Category / Tag
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Analytics (GA4)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-G1DESB7W24"
    anonymize_ip: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
